apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cloud-config: |
    huanghe:
      master: https://127.0.0.1:6443
      insecureSkipTlsVerify: true
      qps: 1e+06
      burst: 1000000
