---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: k8s-cluster-client
  labels:
    app: k8s-client
spec:
  selector:
    matchLabels:
      app: k8s-client
  template:
    metadata:
      labels:
        app: k8s-client
    spec:
      serviceAccountName: cloud-controller-manager
      containers:
        - name: k8s-client
          image: linuxpizi/k8s-client-in-cluster:latest
          imagePullPolicy: Always
          args:
            - /bin/ucloudstack-cloud-controller-manager
            - --v=1
            - --cluster-name=$(CLUSTER_NAME)
            - --cloud-config=$(CLOUD_CONFIG)
            - --cloud-provider=ucloudstack
            - --use-service-account-credentials=true
            - --bind-address=127.0.0.1
          volumeMounts:
            - name: cloud-config-volume
              mountPath: /etc/config
              readOnly: true
          env:
            - name: CLOUD_CONFIG
              value: /etc/config/cloud.yaml
            - name: CLUSTER_NAME
              value: kubernetes
          ports:
            - containerPort: 80
      volumes:
        - name: cloud-config-volume
          configMap:
            name: cloud-config
            items:
              - key: cloud-config
                path: cloud.yaml
